---
services:
  mtest:
    build:
      context: .
      dockerfile: ./docker-files/Dockerfile.proxy
    container_name: mtest
    image: mtest:latest
    restart: always
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
      - ${PROXY_WEB_PORT}:${PROXY_WEB_PORT}
      - ${PROXY_WEB_FILE_PORT}:${PROXY_WEB_FILE_PORT}
    volumes:
      - ./mtest:/src/mtest
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana-oss:9.0.1
    restart: always
    container_name: grafana
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DESIGN: "nette"
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgres

volumes:
  mtest-mitm:
  postgres-data:
  grafana-data:
