---
services:
  #  mtest:
  #    build:
  #      context: .
  #      dockerfile: ./docker-files/Dockerfile.proxy
  #    container_name: mtest
  #    image: mtest:latest
  #    user: ${USER_ID}:${GROUP_ID}
  #    ports:
  #      - 8080:8080
  #      - 8081:8081
  #    volumes:
  #      - type: bind
  #        source: ${MITMPROXY_DIR}
  #        target: /root/.mitmproxy
  #    depends_on:
  #      - mongo

  #  grafana:
  #    build:
  #      context: .
  #      dockerfile: ./docker-files/Dockerfile.grafana
  #    container_name: grafana
  #    image: grafana:latest
  #    ports:
  #      - 9000:3000
  #    volumes:
  #      - grafana-data:/var/lib/grafana
  #    depends_on:
  #      - mongodb
  #      - mtest

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mtest
      MONGO_INITDB_ROOT_PASSWORD: mtest

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mtest
      ME_CONFIG_MONGODB_ADMINPASSWORD: mtest
      ME_CONFIG_MONGODB_URL: mongodb://mtest:mtest@127.0.0.1:27017/
    depends_on:
      - mongo

# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
    external: true
