---
version: "3"

vars:
  PYTHON_VERSION: "3.8.13"
  CERT_FILE: "$HOME/.mitmproxy/mitmproxy-ca-cert.cer"
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"

includes:
  init: .taskfiles/InitTasks.yaml

tasks:
  default:
    cmds:
      - task: run
  run:
    deps: [install]

  install:
    deps: [init:all]
    status:
      - test -d {{.PROJECT_DIR}}/.venv
      - test -f $HOME/.mitmproxy/mitmproxy-ca-cert.cer
      - command -v pyenv
