apiVersion: 1

deleteDatasources:
  - name: Postgres
    orgId: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres
    user: postgres
    database: mtest
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      postgresVersion: 903
      sslmode: disable
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: file-path
      tlsSkipVerify: true
    secureJsonData:
      password: postgres
    readOnly: false
