{
 "title": "Mobile Automated Testing",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# General\n\n\n- Hover over the `i` in the top left of a panel to get a short discription of it.\n- Tables can be filted.\n- You can inspect a specific cell's data in a table by click the eye icon on the end of the cell.\n- You can view seperate pages of results in tables with the pagination at the bottom.\n- Some tables will have more colums if you scroll to the right.\n\n# Proxy data\n\n\nIf you would like to view the proxied data as the test are running please visit this dashboard.\n\n<a href=\"http://localhost:8095\" target=\"_blank\">Mitmproxy Dashboard</a>\n\n# Database\n\n\nIf you would like to view the data this dash board uses, which is stored in a postgres database, please visit this dashboard. **Password is: postgres**\n<a href=\"http://localhost:8888/?pgsql=postgres&username=postgres&db=mtest&ns=public\" target=\"_blank\">Postgres Dasboard(Adminer)</a>\n\n# Useful Commands\n\n\n- Run android tests `task android:test`\n- Run iOS tests `task ios:test`\n- Clear the database `task container:destroy`\n- Restore settings in case of an un-clean shutdown or frozen emulator `task restore`\n- Incase of unknown error `task clean`\n\n# Troubleshooting\n\n\n- If you data isn't showing, refresh the page."
   }
  },
  {
   "title": "All Tests (Appium)",
   "type": "piechart",
   "description": "Test results for both iOS and Android. This only includes Appium tests, NOT data tests.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'passed')) as pass\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'passed') = 'true'\nAND tr.info ->> 'node_id' LIKE '%::test_appium%'"
    },
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'failed')) as fail\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'failed') = 'true'\nAND tr.info ->> 'node_id' LIKE '%::test_appium%'"
    }
   ]
  },
  {
   "title": "All Tests (Data)",
   "type": "piechart",
   "description": "Test results for both iOS and Android. This only includes data tests, NOT Appium tests.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'passed')) as pass\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'passed') = 'true'\nAND tr.info ->> 'node_id' LIKE '%::test_data%'"
    },
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'failed')) as fail\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'failed') = 'true'\nAND tr.info ->> 'node_id' LIKE '%::test_data%'\n"
    }
   ]
  },
  {
   "title": "Android Tests (Appium)",
   "type": "piechart",
   "description": "Test results for Android. This only includes Appium tests, NOT data tests.",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'passed')) as pass\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'passed') = 'true'\nAND platform = 'Android'\nAND tr.info ->> 'node_id' LIKE '%::test_appium%'"
    },
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'failed')) as fail\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'failed') = 'true'\nAND platform = 'Android'\nAND tr.info ->> 'node_id' LIKE '%::test_appium%'"
    }
   ]
  },
  {
   "title": "IOS Tests (Appium)",
   "type": "piechart",
   "description": "Test results for iOS. This only includes Appium tests, NOT data tests.",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'passed')) as pass\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'passed') = 'true'\nAND platform = 'IOS'\nAND tr.info ->> 'node_id' LIKE '%::test_appium%'"
    },
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'failed')) as fail\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'failed') = 'true'\nAND platform = 'IOS'\nAND tr.info ->> 'node_id' LIKE '%::test_appium%'"
    }
   ]
  },
  {
   "title": "Android Tests (Data)",
   "type": "piechart",
   "description": "Test results for Android. This only includes data tests, NOT Appium tests.",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'passed')) as pass\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'passed') = 'true'\nAND platform = 'Android'\nAND tr.info ->> 'node_id' LIKE '%::test_data%'"
    },
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'failed')) as fail\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'failed') = 'true'\nAND platform = 'Android'\nAND tr.info ->> 'node_id' LIKE '%::test_data%'"
    }
   ]
  },
  {
   "title": "IOS Tests (Data)",
   "type": "piechart",
   "description": "Test results for iOS. This only includes data tests, NOT Appium tests.",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'passed')) as pass\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'passed') = 'true'\nAND platform = 'IOS'\nAND tr.info ->> 'node_id' LIKE '%::test_data%'"
    },
    {
     "rawSql": "SELECT\n  now() as time,\n  count((tr.info ->> 'failed')) as fail\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE (tr.info ->> 'failed') = 'true'\nAND platform = 'IOS'\nAND tr.info ->> 'node_id' LIKE '%::test_data%'"
    }
   ]
  },
  {
   "title": "Total: Analytics Calls (All test runs)",
   "type": "stat",
   "description": "Analytics calls captured. This is for all test runs stored in the postgres database.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT pr.info -> 'content' ->> 'batch' as batched_data\nFROM proxy_request pr\nJOIN test_results tr on tr.info ->> 'test_id' = pr.info ->> 'test_id'\nJOIN test_id ti on ti.test_id = pr.info ->> 'test_id'\nAND tr.info ->> 'node_id' NOT LIKE '%test_data%'\nWHERE pr.info -> 'content' -> 'batch' IS NOT NULL\n"
    }
   ]
  },
  {
   "title": "Total: Proxy Response (All test runs)",
   "type": "stat",
   "description": "All proxy responses captured by the proxy. This is for ALL test runs.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "rawSql": "SELECT id\nFROM proxy_response" }
   ]
  },
  {
   "title": "Total: Proxy Request (All test runs)",
   "type": "stat",
   "description": "All proxy requests captured by the proxy. This is for ALL test runs.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "rawSql": "SELECT id\nFROM proxy_request" }
   ]
  },
  {
   "title": "Total: Test runs stored in database",
   "type": "stat",
   "description": "The total amount of test \"runs\", NOT the total amount of individual tests. ",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT test_results.info ->> 'test_id'\nFROM test_results\nGROUP BY test_results.info ->> 'test_id'"
    }
   ]
  },
  {
   "title": "Total: Android test runs",
   "type": "stat",
   "description": "The total amount of test \"runs\" for Android, NOT the total amount of individual tests. ",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT tr.info ->> 'test_id'\nFROM test_results tr\nJOIN test_id ti ON ti.test_id = tr.info ->> 'test_id'\nWHERE ti.platform = 'Android'\nGROUP BY tr.info ->> 'test_id'"
    }
   ]
  },
  {
   "title": "Total: iOS test runs",
   "type": "stat",
   "description": "The total amount of test \"runs\" for iOS, NOT the total amount of individual tests. ",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT tr.info ->> 'test_id'\nFROM test_results tr\nJOIN test_id ti ON ti.test_id = tr.info ->> 'test_id'\nWHERE ti.platform = 'IOS'\nGROUP BY tr.info ->> 'test_id'"
    }
   ]
  },
  {
   "title": "Latest Test ID",
   "type": "stat",
   "description": "The test id of the last run test.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT test_id\nFROM test_id\nORDER BY timestamp DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Data Test Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Android - PASS",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT\n  platform,\n  test_id,\n  (tr.info ->> 'node_id') as test,\n  ROUND((tr.info ->> 'duration')::FLOAT) duration\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE platform = 'Android'\nAND info ->> 'outcome' = 'passed'\nAND info ->> 'node_id' LIKE '%::test_data%'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "iOS - PASS",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT\n  platform,\n  test_id,\n  (tr.info ->> 'node_id') as test,\n  ROUND((tr.info ->> 'duration')::FLOAT) duration\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE platform = 'IOS'\nAND info ->> 'outcome' = 'passed'\nAND info ->> 'node_id' LIKE '%::test_data%'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Android - FAIL",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT\n  platform,\n  test_id,\n  (tr.info ->> 'node_id') as test,\n  ROUND((tr.info ->> 'duration')::FLOAT) duration\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE platform = 'Android'\nAND info ->> 'outcome' = 'failed'\nAND info ->> 'node_id' LIKE '%::test_data%'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "iOS - FAIL",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT\n  platform,\n  test_id,\n  (tr.info ->> 'node_id') as test,\n  ROUND((tr.info ->> 'duration')::FLOAT) duration\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE platform = 'IOS'\nAND info ->> 'outcome' = 'failed'\nAND info ->> 'node_id' LIKE '%::test_data'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Appium Test Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Android - PASS",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\n  platform,\n  test_id,\n  (tr.info ->> 'node_id') as test,\n  ROUND((tr.info ->> 'duration')::FLOAT) duration\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE platform = 'Android'\nAND info ->> 'outcome' = 'passed'\nAND info ->> 'node_id' LIKE '%::test_appium%'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "iOS - PASS",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\n  platform,\n  test_id,\n  (tr.info ->> 'node_id') as test,\n  ROUND((tr.info ->> 'duration')::FLOAT) duration\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE platform = 'IOS'\nAND info ->> 'outcome' = 'passed'\nAND info ->> 'node_id' LIKE '%::test_appium%'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Android - FAIL",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "rawSql": "SELECT\n  platform,\n  test_id,\n  (tr.info ->> 'node_id') as test,\n  ROUND((tr.info ->> 'duration')::FLOAT) duration\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE platform = 'Android'\nAND info ->> 'outcome' = 'failed'\nAND info ->> 'node_id' LIKE '%::test_appium%'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "iOS - FAIL",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "rawSql": "SELECT\n  platform,\n  test_id,\n  (tr.info ->> 'node_id') as test,\n  ROUND((tr.info ->> 'duration')::FLOAT) duration\nFROM test_id ti\nJOIN test_results tr ON (tr.info ->> 'test_id') = ti.test_id\nWHERE platform = 'IOS'\nAND info ->> 'outcome' = 'failed'\nAND info ->> 'node_id' LIKE '%::test_appium%'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Analytics Call Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Analytics Calls",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT ti.platform,\npr.info ->> 'test_id' as test_id,\n(tr.info ->> 'node_id') as test,\ntr.info ->> 'outcome' as outcome,\n(elem ->> 'properties') as properties\nFROM proxy_request pr\nJOIN test_results tr on tr.info ->> 'test_id' = pr.info ->> 'test_id'\nJOIN test_id ti on ti.test_id = pr.info ->> 'test_id'\nCROSS JOIN json_array_elements(CAST(pr.info -> 'content' ->> 'batch' AS json)) elem\nWHERE pr.info -> 'content' -> 'batch' IS NOT NULL\nAND tr.info ->> 'node_id' NOT LIKE '%test_data%'\nAND elem -> 'properties' IS NOT NULL\n"
      }
     ]
    },
    {
     "title": "Raw Analytics Calls",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "rawSql": "SELECT ti.platform,\npr.info ->> 'test_id' as test_id,\n(tr.info ->> 'node_id') as test,\ntr.info ->> 'outcome' as outcome,\npr.info -> 'content' ->> 'batch' as batched_data\nFROM proxy_request pr\nJOIN test_results tr on tr.info ->> 'test_id' = pr.info ->> 'test_id'\nJOIN test_id ti on ti.test_id = pr.info ->> 'test_id'\nAND tr.info ->> 'node_id' NOT LIKE '%test_data%'\nWHERE pr.info -> 'content' -> 'batch' IS NOT NULL\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Formated Proxy Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Data",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  info ->> 'test_id' as test_id,\n  info ->> 'timestamp' as request_timestamp,\n  info ->> 'host' as host,\n  info ->> 'port' as port,\n  info ->> 'method' as method,\n  info ->> 'schema' as schema,\n  info ->> 'authority' as authority,\n  info ->> 'path' as path,\n  info ->> 'http_version' as http_version,\n  info ->> 'headers' as headers,\n  info ->> 'content' as content,\n  info ->> 'trailers' as trailers,\n  info ->> 'timestamp_start' as timestamp_start,\n  info ->> 'timestamp_end' as timestamp_end\nFROM proxy_request\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Response Data",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  info ->> 'test_id' as test_id,\n  info ->> 'timestamp' as request_timestamp,\n  info ->> 'http_version' as http_version,\n  info ->> 'status_code' as status_code,\n  info ->> 'reason' as reason,\n  info ->> 'headers' as headers,\n  info ->> 'content' as content,\n  info ->> 'trailers' as trailers,\n  info ->> 'timestamp_start' as timestamp_start,\n  info ->> 'timestamp_end' as timestamp_end\nFROM proxy_response\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Proxy Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Data (Raw)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  info\nFROM proxy_request\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Response Data (Raw)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  info\nFROM proxy_response\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}